language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t sharky84/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true sharky84/react-test npm run test

after_success:
    - docker build -t sharky84/multi-client ./client
    - docker build -t sharky84/multi-nginx ./nginx
    - docker build -t sharky84/multi-server ./server
    - docker build -t sharky84/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take docker images and push them to docker hub
    - docker push  sharky84/multi-client
    - docker push  sharky84/multi-nginx
    - docker push  sharky84/multi-server
    - docker push  sharky84/multi-worker
