language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t markosarkanj/docker-react-multicontainer -f Dockerfile.dev .

script:
    - docker run -e CI=true markosarkanj/docker-react-multicontainer npm run test
